language: android
dist: trusty
env:
  global:
    - ANDROID_TARGET=android-16
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=27
android:
  components:
  - tools
  - platform-tools
  - android-${ANDROID_TARGET}
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
    - 'android-sdk-license-.+'
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
script:
  - ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)